version: "3.6"
services:
  city:
    build:
      context: ./services/city
    environment:
      MONGODB_URI: "mongodb://mongo:27017/weather"
    depends_on:
      - mongo
  history:
    build:
      context: ./services/history
    environment:
      MONGODB_URI: "mongodb://mongo:27017/weather"
    depends_on:
      - mongo
  client:
    build:
      context: ./client
    volumes:
      - ./client/src:/var/www/client/src
      - ./client/webpack:/var/www/client/webpack
    environment:
      NODE_ENV: development
  nginx:
    build:
      context: ./tools/nginx
    ports:
      - "3003:80"
    depends_on:
      - city
      - history
      - client
  mongo:
    image: mongo:4
    command: mongod --quiet
    ports:
      - 27017:27017
