version: '3.6'
services:
  server:
    build:
      context: ./server
    volumes:
     - ./server/src:/var/www/server/src
     - ./server/db.sqlite3:/var/www/server/db.sqlite3
    environment:
      NODE_ENV: development
  client:
    build:
      context: ./client
    volumes:
     - ./client/src:/var/www/client/src
     - ./client/webpack:/var/www/client/webpack
    environment:
      NODE_ENV: development
  nginx:
    build:
      context: ./tools/nginx
    ports:
     - "3003:80"
    depends_on:
     - server
     - client
