export const WEATHER_PAGE_LOADED = 'WEATHER_PAGE_LOADED'

export const WEATHER_RESET_CITY = 'WEATHER_RESET_CITY'

export const WEATHER_MONTH_VISIBLE = 'WEATHER_MONTH_VISIBLE'

export const WEATHER_MONTH_DATA_REQUEST = 'WEATHER_MONTH_DATA_REQUEST'
export const WEATHER_MONTH_DATA_RESPONSE = 'WEATHER_MONTH_DATA_RESPONSE'
export const WEATHER_MONTH_DATA_ERROR = 'WEATHER_MONTH_DATA_ERROR'
